#Use the new container-based infrastructure
os: linux
dist: xenial
language: go

#Install the apt prerequisites
addons:
  apt_packages:
    - python-pygments

#Set the build environment
env:
  - HUGOV=0.88.1

#Clean and don't fail
install:
  - rm -rf public || exit 0

#Download Hugo
before_script:
  - curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo nvm use 16.10.0
  - npm i -g grunt-cli
  - npm i -g yarn
  - yarn set version latest
  - yarn install --no-lockfile
  - grunt content-index
  - mkdir binaries
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGOV}/hugo_${HUGOV}_Linux-64bit.tar.gz" -O binaries/hugo_${HUGOV}_Linux-64bit.tar.gz
  - cd binaries
  - tar -xzf hugo_${HUGOV}_Linux-64bit.tar.gz
  - chmod +x hugo
  - cd ..

#Build the website
script:
  - binaries/hugo --minify

#Deploy to GitHub pages
deploy:
  strategy: git 
  provider: pages
  local_dir: public
  token: $GITHUB_TOKEN
  keep_history: true
  fqdn: sbpp.dev
  target_branch: master
  on:
    branch: src

