#Use the new container-based infrastructure
sudo: false
language: go

#Install the apt prerequisites
addons:
  apt_packages:
    - python-pygments

#Set the build environment
env:
  - HUGOV=0.59.1

#Clean and don't fail
install:
  - rm -rf public || exit 0

#Download Hugo
before_script:
  - curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm i -g grunt-cli
  - npm i -g yarn
  - yarn
  - grunt content-index
  - mkdir binaries
  - wget "https://github.com/gohugoio/hugo/releases/download/v${HUGOV}/hugo_${HUGOV}_Linux-64bit.tar.gz" -O binaries/hugo_${HUGOV}_Linux-64bit.tar.gz
  - cd binaries
  - tar -xzf hugo_${HUGOV}_Linux-64bit.tar.gz
  - chmod +x hugo
  - cd ..

#Build the website
script:
  - binaries/hugo --minify

#Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN
  keep-history: true
  fqdn: sbpp.dev
  target-branch: master
  on:
    branch: src

